configfile: "defaults/config.yaml"

rule all:
    input:
        auspice_json = config["files"]["auspice_json"],
        nextclade_dataset = "dataset/tree.json",
        test_dataset = "test_output",

include: "rules/prepare_sequences.smk"
include: "rules/construct_phylogeny.smk"
include: "rules/annotate_phylogeny.smk"
include: "rules/export.smk"
include: "rules/assemble_dataset.smk"

rule clean:
    params:
        targets = [
            ".snakemake",
            "auspice",
            "benchmarks",
            "data",
            "dataset",
            "logs",
            "results",
            "test_output",
        ]
    shell:
        """
        rm -rfv {params.targets}
        """
