configfile: "defaults/config.yaml"

gene = ["genome", "prM-E"]

rule all:
    input:
        auspice_json=expand("auspice/yellow-fever-virus_{gene}.json", gene=gene),


include: "rules/prepare_sequences.smk"
include: "rules/construct_phylogeny.smk"
include: "rules/annotate_phylogeny.smk"
include: "rules/export.smk"

rule clean:
    params:
        targets = [
            ".snakemake",
            "auspice",
            "data",
            "logs",
            "results",
            ]
    shell:
        """
        rm -rfv {params.targets}
        """
