builds:
    - "genome"
    - "prM-E"
strain_id_field: "accession"
files:
    description: "defaults/description.md"
    genome:
        auspice_config: "defaults/auspice_config_genome.json"
        exclude: "defaults/dropped_strains_genome.txt"
        genemap: "defaults/genemap_genome.gff"
        include: "defaults/include_strains_genome.txt"
        reference: "defaults/reference_genome.fasta"
    prM-E:
        auspice_config: "defaults/auspice_config_prM-E.json"
        exclude: "defaults/dropped_strains_prM-E.txt"
        genemap: "defaults/genemap_prM-E.gff"
        include: "defaults/include_strains_prM-E.txt"
        reference: "defaults/reference_prM-E.fasta"
filter:
    group_by: "country year"
    min_date: "1900-01-01"
    genome:
        min_length: 9000
        sequences_per_group: 20
    prM-E:
        min_length: 600
        sequences_per_group: 200
refine:
    coalescent: "opt"
    date_inference: "marginal"
    clock_filter_iqd: 4
    clock_rate: 0.0002
    clock_std_dev: 0.00001
ancestral:
    inference: "joint"
traits:
    columns: "clade region"
tip_frequencies:
    min_date: "2017-01-01"
    max_date: "6M"
    narrow_bandwidth: 0.2
    wide_bandwidth: 0.6
export:
    metadata_columns: "clade region"
